name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -scheme FinancialEntities \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' \
          -quiet \
          -skipPackagePluginValidation \
          -skipMacroValidation